CREATE TABLE [dbo].[INVENTDIM1] (
    [INVENTDIMID]      NVARCHAR (40) NOT NULL,
    [INVENTBATCHID]    NVARCHAR (40) NOT NULL,
    [WMSLOCATIONID]    NVARCHAR (20) NOT NULL,
    [WMSPALLETID]      NVARCHAR (36) NOT NULL,
    [INVENTSERIALID]   NVARCHAR (40) NOT NULL,
    [INVENTLOCATIONID] NVARCHAR (20) NOT NULL,
    [CONFIGID]         NVARCHAR (20) NOT NULL,
    [INVENTSIZEID]     NVARCHAR (20) NOT NULL,
    [INVENTCOLORID]    NVARCHAR (20) NOT NULL,
    [DATAAREAID]       NVARCHAR (6)  NOT NULL,
    [RECVERSION]       INT           NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [INVENTDIMID] ASC)
);


GO

