CREATE TABLE [dbo].[JSCSRRECEIPTMSTR] (
    [RECEIPTNO]              NVARCHAR (24)   NOT NULL,
    [STATUS]                 INT             NOT NULL,
    [VOUCHER]                NVARCHAR (40)   NOT NULL,
    [ACCOUNTNUM]             NVARCHAR (40)   NOT NULL,
    [CONTRACT]               NVARCHAR (64)   NOT NULL,
    [ITEMGROUPID]            NVARCHAR (20)   NOT NULL,
    [LOCATIONID]             NVARCHAR (20)   NOT NULL,
    [PURCHMETHOD]            NVARCHAR (24)   NOT NULL,
    [EFFECTIVE]              DATETIME        NOT NULL,
    [HAULER]                 NVARCHAR (40)   NOT NULL,
    [TRUCK]                  NVARCHAR (40)   NOT NULL,
    [DRIVER]                 NVARCHAR (40)   NOT NULL,
    [TRAILER1]               NVARCHAR (40)   NOT NULL,
    [TRAILER2]               NVARCHAR (40)   NOT NULL,
    [FIELDIDTAG]             NVARCHAR (20)   NOT NULL,
    [BILLOFLADING]           NVARCHAR (20)   NOT NULL,
    [JOURNALID]              NVARCHAR (40)   NOT NULL,
    [SETTLEVALUE]            NUMERIC (13, 2) NOT NULL,
    [FREIGHTSTATUS]          INT             NOT NULL,
    [FREIGHTVOUCHER]         NVARCHAR (40)   NOT NULL,
    [FREIGHTPAID]            NUMERIC (13, 2) NOT NULL,
    [REGION]                 NVARCHAR (24)   NOT NULL,
    [SEASON]                 NVARCHAR (24)   NOT NULL,
    [DEL_SOURCE]             NVARCHAR (40)   NOT NULL,
    [DEL_ADVANCEPERCENT]     NUMERIC (13, 2) NOT NULL,
    [JSCSRINVJOURNALNUM]     NVARCHAR (40)   NOT NULL,
    [JSINVSETTLEMENTJOURNUM] NVARCHAR (40)   NOT NULL,
    [SCALETICKETID]          NVARCHAR (40)   NOT NULL,
    [COMMENTS]               NTEXT           NOT NULL,
    [RECEIPTTYPE]            INT             NOT NULL,
    [ORIGRECEIPT]            NVARCHAR (24)   NOT NULL,
    [HARVESTERINVOICE]       NVARCHAR (20)   NOT NULL,
    [CORRECTED]              INT             NOT NULL,
    [MODIFIEDDATE]           DATETIME        NOT NULL,
    [MODIFIEDTIME]           INT             NOT NULL,
    [MODIFIEDBY]             NVARCHAR (10)   NOT NULL,
    [MODIFIEDTRANSACTIONID]  BIGINT          NOT NULL,
    [CREATEDDATE]            DATETIME        NOT NULL,
    [CREATEDTIME]            INT             NOT NULL,
    [CREATEDBY]              NVARCHAR (10)   NOT NULL,
    [CREATEDTRANSACTIONID]   BIGINT          NOT NULL,
    [DATAAREAID]             NVARCHAR (6)    NOT NULL,
    [RECVERSION]             INT             NOT NULL,
    [RECID]                  BIGINT          NOT NULL,
    [REJECTRECEIPTNO]        NVARCHAR (24)   NOT NULL,
    PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [RECEIPTNO] ASC)
);


GO

