CREATE TABLE [dbo].[jsvarietytable1] (
    [VARIETY]     NVARCHAR (20)  NOT NULL,
    [DESCRIPTION] NVARCHAR (120) NOT NULL,
    [RECVERSION]  INT            NOT NULL,
    [RECID]       BIGINT         NOT NULL,
    PRIMARY KEY CLUSTERED ([VARIETY] ASC)
);


GO

